import test from "node:test";
import assert from "node:assert/strict";
import { chromium } from "playwright";
import { extractHighlightedTextFromPage } from "../src/highlights.js";

test("extracts highlighted spans from a ZeroGPT-like result page", async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();

  try {
    await page.setContent(`
      <main>
        <p>Before result should not count.</p>
        <section>
          <div>Your Text is Likely Human written, may include parts generated by AI/GPT</div>
          <div>32% AI GPT*</div>
          <div class="highlights-container">
            <span class="highlights">
              Plain parent text should not count.
              <mark class="highlight">Framework Computer is a small computer company built around a repairable laptop idea.</mark>
              <span style="background: rgb(255, 242, 0)">Gartner reported that in 2025 Lenovo had 27.2 percent of worldwide PC shipments.</span>
            </span>
          </div>
          <div>147 Characters</div>
          <div>23 Words</div>
        </section>
      </main>
    `);

    const highlights = await extractHighlightedTextFromPage(page);
    assert.deepEqual(highlights, [
      "Framework Computer is a small computer company built around a repairable laptop idea.",
      "Gartner reported that in 2025 Lenovo had 27.2 percent of worldwide PC shipments."
    ]);
  } finally {
    await browser.close();
  }
});
