import { MAX_ZEROGPT_CHARS } from "./constants.js";

export function splitTextForZeroGPT(text, options = {}) {
  const source = String(text ?? "");
  const maxChars = options.maxChars ?? MAX_ZEROGPT_CHARS;
  if (!Number.isFinite(maxChars) || maxChars <= 0) {
    throw new Error("maxChars must be a positive number");
  }

  const lineStarts = buildLineStarts(source);
  const chunks = [];
  let cursor = 0;

  while (cursor < source.length) {
    const hardEnd = Math.min(cursor + maxChars, source.length);
    const rawEnd = hardEnd >= source.length ? source.length : findChunkBreak(source, cursor, hardEnd);
    const trimmed = trimRange(source, cursor, rawEnd);

    if (trimmed.start < trimmed.end) {
      chunks.push({
        index: chunks.length + 1,
        text: source.slice(trimmed.start, trimmed.end),
        startOffset: trimmed.start,
        endOffset: trimmed.end,
        startLine: offsetToLine(lineStarts, trimmed.start),
        inputLength: trimmed.end - trimmed.start
      });
    }

    cursor = rawEnd > cursor ? rawEnd : hardEnd;
  }

  return chunks;
}

export function deriveVerdict(aiPercentage) {
  if (aiPercentage === null || aiPercentage === undefined || Number.isNaN(aiPercentage)) {
    return "Unknown verdict";
  }

  if (aiPercentage < 10) return "Your Text is Human written";
  if (aiPercentage < 50) return "Your Text is Likely Human written, may include parts generated by AI/GPT";
  if (aiPercentage < 80) return "Your Text is Likely AI/GPT generated";
  return "Your Text is Most Likely AI/GPT generated";
}

export function shiftFlaggedLines(flagged, chunk) {
  return (flagged ?? []).map((item) => ({
    ...item,
    lineStart: item.lineStart === null ? null : chunk.startLine + item.lineStart - 1,
    lineEnd: item.lineEnd === null ? null : chunk.startLine + item.lineEnd - 1
  }));
}

export function compactChunkResult(result, chunk) {
  return {
    index: chunk.index,
    inputLength: chunk.inputLength,
    aiPercentage: result.aiPercentage,
    verdict: result.verdict,
    wordCount: result.wordCount,
    characterCount: result.characterCount,
    notice: result.notice,
    flaggedCount: result.flagged?.length ?? 0
  };
}

export function combineChunkResults(chunkResults) {
  const chunks = chunkResults.map(({ chunk, result }) => compactChunkResult(result, chunk));
  const weighted = chunkResults.filter(({ result }) => Number.isFinite(result.aiPercentage));
  const totalWeight = weighted.reduce((sum, { chunk }) => sum + chunk.inputLength, 0);
  const aiPercentage =
    totalWeight > 0
      ? roundOne(weighted.reduce((sum, { chunk, result }) => sum + result.aiPercentage * chunk.inputLength, 0) / totalWeight)
      : null;

  const flagged = chunkResults
    .flatMap(({ chunk, result }) => shiftFlaggedLines(result.flagged, chunk))
    .sort((a, b) => {
      const aLine = a.lineStart ?? Number.POSITIVE_INFINITY;
      const bLine = b.lineStart ?? Number.POSITIVE_INFINITY;
      return aLine - bLine || (a.lineEnd ?? Number.POSITIVE_INFINITY) - (b.lineEnd ?? Number.POSITIVE_INFINITY);
    });

  const wordCount = sumNullable(chunkResults.map(({ result }) => result.wordCount));
  const characterCount = sumNullable(chunkResults.map(({ result }) => result.characterCount));
  const warnings = [...new Set(chunkResults.flatMap(({ result }) => result.warnings ?? []))];
  const notices = [...new Set(chunkResults.map(({ result }) => result.notice).filter(Boolean))];

  return {
    source: "zerogpt",
    url: chunkResults[0]?.result.url,
    split: chunkResults.length > 1,
    chunkCount: chunkResults.length,
    chunks,
    inputLength: chunkResults.reduce((sum, { chunk }) => sum + chunk.inputLength, 0),
    checkedAt: new Date().toISOString(),
    flagged,
    warnings,
    verdict: deriveVerdict(aiPercentage),
    aiPercentage,
    wordCount,
    characterCount,
    notice: notices.length ? notices.join(" | ") : null
  };
}

function findChunkBreak(source, start, hardEnd) {
  const preferredStart = start + Math.floor((hardEnd - start) * 0.9);
  const candidates = [
    lastIndexAfter(source, "\n\n", preferredStart, hardEnd, 2),
    lastIndexAfter(source, "\n", preferredStart, hardEnd, 1),
    lastSentenceBreak(source, preferredStart, hardEnd),
    lastIndexAfter(source, " ", preferredStart, hardEnd, 1)
  ];

  return candidates.find((candidate) => candidate > start) ?? hardEnd;
}

function lastIndexAfter(source, needle, min, max, advance) {
  const index = source.lastIndexOf(needle, max - 1);
  return index >= min ? index + advance : -1;
}

function lastSentenceBreak(source, min, max) {
  let best = -1;
  const pattern = /[.!?][)"'\]]?\s+/g;
  pattern.lastIndex = min;

  for (let match = pattern.exec(source); match && match.index < max; match = pattern.exec(source)) {
    const end = match.index + match[0].length;
    if (end <= max) best = end;
  }

  return best;
}

function trimRange(source, start, end) {
  let trimmedStart = start;
  let trimmedEnd = end;

  while (trimmedStart < trimmedEnd && /\s/.test(source[trimmedStart])) trimmedStart += 1;
  while (trimmedEnd > trimmedStart && /\s/.test(source[trimmedEnd - 1])) trimmedEnd -= 1;

  return { start: trimmedStart, end: trimmedEnd };
}

function buildLineStarts(source) {
  const lineStarts = [0];
  for (let index = 0; index < source.length; index += 1) {
    if (source[index] === "\n") lineStarts.push(index + 1);
  }
  return lineStarts;
}

function offsetToLine(lineStarts, offset) {
  let low = 0;
  let high = lineStarts.length - 1;

  while (low <= high) {
    const mid = Math.floor((low + high) / 2);
    if (lineStarts[mid] <= offset) low = mid + 1;
    else high = mid - 1;
  }

  return high + 1;
}

function sumNullable(values) {
  const finite = values.filter((value) => Number.isFinite(value));
  return finite.length ? finite.reduce((sum, value) => sum + value, 0) : null;
}

function roundOne(value) {
  return Math.round(value * 10) / 10;
}
