import { chromium } from "playwright";
import { extractHighlightedTextFromPage } from "./highlights.js";
import { mapHighlightedText } from "./line-map.js";
import { checkZeroGPTInput as checkInput } from "./input.js";

const DEFAULT_URL = "https://www.zerogpt.com/";

export async function checkZeroGPTInput(inputOptions, runOptions = {}) {
  return checkInput(inputOptions, runOptions, detectWithZeroGPT);
}

export async function detectWithZeroGPT(text, options = {}) {
  const input = String(text ?? "").trim();
  if (!input) throw new Error("Input text is empty");

  const timeoutMs = options.timeoutMs ?? 60000;
  const browser = await chromium.launch({
    headless: !options.headed
  });

  try {
    const page = await browser.newPage({
      viewport: { width: 1365, height: 900 }
    });
    page.setDefaultTimeout(timeoutMs);

    await page.goto(options.url ?? DEFAULT_URL, { waitUntil: "domcontentloaded" });
    await dismissConsent(page);

    const textbox = page.getByRole("textbox", {
      name: /enter text to check for ai/i
    });
    await textbox.fill(input);

    await page.getByRole("button", { name: /detect text/i }).click();
    await waitForResult(page, timeoutMs);

    const [extracted, highlightedText] = await Promise.all([
      extractResult(page, {
        includeRawText: options.includeRawText === true
      }),
      extractHighlightedTextFromPage(page)
    ]);
    const flagged = mapHighlightedText(input, highlightedText);
    const warnings = [];
    if ((extracted.verdict || extracted.aiPercentage !== null) && highlightedText.length === 0) {
      warnings.push("Highlights were not found; flagged line ranges are unavailable.");
    }
    if (flagged.some((item) => item.lineStart === null || item.lineEnd === null)) {
      warnings.push("Some highlighted text could not be mapped to source lines.");
    }

    return {
      source: "zerogpt",
      url: page.url(),
      inputLength: input.length,
      checkedAt: new Date().toISOString(),
      flagged,
      warnings,
      ...extracted
    };
  } finally {
    await browser.close();
  }
}

async function dismissConsent(page) {
  const consentFrame = page.frameLocator('iframe[title="SP Consent Message"]');
  const reject = consentFrame.getByRole("button", { name: /reject all/i });
  const accept = consentFrame.getByRole("button", { name: /^accept$/i });

  try {
    await reject.click({ timeout: 5000 });
  } catch {
    try {
      await accept.click({ timeout: 1500 });
    } catch {
      // The dialog is regional and does not always appear.
    }
  }
}

async function waitForResult(page, timeoutMs) {
  await page.waitForFunction(
    () => /Your Text is/i.test(document.body.innerText),
    undefined,
    { timeout: timeoutMs }
  );
}

async function extractResult(page, options = {}) {
  return page.evaluate((evaluateOptions) => {
    const bodyText = document.body.innerText.replace(/\u00a0/g, " ");
    const compact = bodyText
      .split("\n")
      .map((line) => line.trim())
      .filter(Boolean);

    const verdict =
      compact.find((line) => /^Your Text is/i.test(line)) ??
      compact.find((line) => /human written|ai generated|generated by ai/i.test(line)) ??
      null;

    const percentageMatch = bodyText.match(/(\d+(?:\.\d+)?)\s*%\s*AI\s*GPT/i);
    const wordsMatches = [...bodyText.matchAll(/(\d[\d,]*)\s+Words\b/gi)];
    const charsMatches = [...bodyText.matchAll(/(\d[\d,]*)\s+Characters\b/gi)];
    const wordsMatch = wordsMatches.at(-1);
    const charsMatch = charsMatches.at(-1);
    const notice =
      compact.find((line) => /Please input more text/i.test(line))?.replace(/\*/g, "") ??
      null;

    const result = {
      verdict,
      aiPercentage: percentageMatch ? Number(percentageMatch[1]) : null,
      wordCount: wordsMatch ? Number(wordsMatch[1].replaceAll(",", "")) : null,
      characterCount: charsMatch ? Number(charsMatch[1].replaceAll(",", "")) : null,
      notice
    };

    if (evaluateOptions.includeRawText) {
      result.rawText = compact.slice(0, 40).join("\n");
    }

    return result;
  }, options);
}

export function toCompactZeroGPTResult(result) {
  return {
    verdict: result.verdict,
    aiPercentage: result.aiPercentage,
    wordCount: result.wordCount,
    characterCount: result.characterCount,
    notice: result.notice
  };
}
